### ISSUE TITLE
[EOEPCA/IAM] Amend Helm chart

### ISSUE THREAD

**Issue by w-jfe** [EOEPCA/iam#64]
* Add global HTTP-to-HTTPS redirect in a `ApisixGlobalRule`
* Add `apisix.pluginAttrs.redirect.https_port=443` property to default values.yaml

**Comment by rconway** [comment]
I found an unwanted side-effect with using the `redirect` `http_to_https` plugin in `ApisixGlobalRule` - which interferes with the function of the Cert Manager letsencrypt challenge using http (not https).

Anyway, I think I found the solution is to use a `filter` on the plugin so that it does not apply for the acme challenge...

```
apiVersion: apisix.apache.org/v2
kind: ApisixGlobalRule
metadata:
  name: redirect-to-tls
spec:
  plugins:
    - name: redirect
      enable: true
      config:
        http_to_https: true
        _meta:
          filter:
            # Exclude paths used by letsencrypt http challenge
            - [ 'request_uri', '!', '~*', '^/\.well-known/acme-challenge.*' ]
```
